/*      jconjtest.c     */
/* JNetHack may be freely redistributed.  See license for details. */

/*
 * Golden-output harness for japanese/jconj.c.
 *
 * Phase 1 of UTF8-PLAN.md rewrites jconjsub() from "overwrite the last two
 * bytes" to "replace the last character", because under UTF-8 a hiragana is
 * three bytes and the arithmetic no longer lands where it used to.  That is
 * the one part of the migration a machine cannot check by inspection: the
 * function encodes Japanese verb conjugation, and a wrong answer is a wrong
 * answer, not a crash.
 *
 * So this prints every conjugation the table can produce, and test/
 * jconjtest.sh diffs it against test/jconj.golden.  The baseline is taken
 * before the rewrite; the rewrite is correct exactly when the diff is empty.
 *
 * The verb list is not duplicated here.  jconjtest.sh extracts it from
 * jconj.c at build time into jconj_verbs.h, so the harness always covers
 * whatever the table currently holds -- including entries added later.
 *
 * The suffixes below are chosen to reach every branch in jconjsub(), not
 * just the ones the game happens to use.  jconjsub() dispatches on the first
 * character of the suffix: TO, NA, TA, TE, BA, RE, MA, and a default that
 * falls through.  Each is represented, plus the multi-character forms the
 * game passes and the "REBA" form that SAHEN tests for separately.
 */

#include <stdio.h>
#include <string.h>

#include "hack.h"

/* generated by test/jconjtest.sh from japanese/jconj.c */
#include "jconj_verbs.h"

/*
 * Suffixes, in whatever encoding jconj.c's literals are in.  They are given
 * as byte escapes rather than as literal text so that this file stays pure
 * ASCII and does not itself have to be converted in Phase 3 -- the harness
 * has to keep working across the encoding switch, which is the whole point
 * of having it.
 *
 * jconjtest.sh regenerates these in the current encoding, for the same
 * reason it regenerates the verb list.
 */
#include "jconj_sfx.h"

int
main()
{
    int i, j;

    /*
     * One line per (verb, suffix).  Fixed order, so a diff points straight
     * at the entry that moved.
     */
    for (i = 0; jconj_verbs[i]; i++) {
        for (j = 0; jconj_sfx[j]; j++)
            (void) printf("jconj\t%s\t%s\t%s\n",
                          jconj_verbs[i], jconj_sfx[j],
                          jconj(jconj_verbs[i], jconj_sfx[j]));

        (void) printf("jcan\t%s\t-\t%s\n",
                      jconj_verbs[i], jcan(jconj_verbs[i]));
        (void) printf("jcannot\t%s\t-\t%s\n",
                      jconj_verbs[i], jcannot(jconj_verbs[i]));
        (void) printf("jpast\t%s\t-\t%s\n",
                      jconj_verbs[i], jpast(jconj_verbs[i]));
        (void) printf("jconj_adj\t%s\t-\t%s\n",
                      jconj_verbs[i], jconj_adj(jconj_verbs[i]));
    }

    /*
     * jconj() also matches on a suffix of the input, so that a whole phrase
     * ending in a known verb conjugates.  That second loop in jconj() is
     * easy to break while rearranging the first, so exercise it: each verb
     * with a prefix glued on.  The prefix is ASCII, which is the awkward
     * case for anything that walks backwards from the end of the string.
     */
    for (i = 0; jconj_verbs[i]; i++) {
        char buf[512];

        (void) strcpy(buf, "xy");
        (void) strcat(buf, jconj_verbs[i]);
        for (j = 0; jconj_sfx[j]; j++)
            (void) printf("phrase\t%s\t%s\t%s\n",
                          buf, jconj_sfx[j], jconj(buf, jconj_sfx[j]));
    }

    /* An unknown verb must come back untouched rather than being mangled. */
    for (j = 0; jconj_sfx[j]; j++)
        (void) printf("unknown\tzzz\t%s\t%s\n",
                      jconj_sfx[j], jconj("zzz", jconj_sfx[j]));

    return 0;
}

/*jconjtest.c*/
