/*      jlibtest.c      */
/* JNetHack may be freely redistributed.  See license for details. */

/*
 * Golden-output harness for the multibyte parts of japanese/jlib.c:
 * is_kanji1(), is_kanji2(), split_japanese() and jrndm_replace().
 *
 * Same arrangement as test/jconjtest.c, and for the same reason.  Phase 1
 * of UTF8-PLAN.md rewrites these in terms of characters rather than byte
 * pairs, and split_japanese() in particular is line-breaking logic with
 * kinsoku rules -- a change there shows up as text wrapping in a slightly
 * different place, which is exactly the kind of regression that survives
 * a casual look at the screen.  So record what it does first.
 *
 * jlib.c links against four things from the game proper; they are stubbed
 * at the bottom.  rn2() is a fixed sequence rather than the real generator
 * so that jrndm_replace(), which is deliberately random, still produces a
 * reproducible transcript.
 *
 * Test strings come in through a generated header, so this file stays pure
 * ASCII and does not need converting in Phase 3.
 */

#include <stdio.h>
#include <string.h>

#include "hack.h"
#include "mbchar.h"

/* generated by test/jlibtest.sh, in whatever encoding jlib.c is written in */
#include "jlib_strings.h"

/* --- is_kanji1 / is_kanji2 ----------------------------------------- */

static void
dump_boundaries()
{
    int i, j;

    for (i = 0; jlib_strings[i]; i++) {
        const char *s = jlib_strings[i];
        int len = (int) strlen(s);

        /*
         * Every byte offset, not just the interesting ones.  These two
         * functions are asked about offsets that came from byte arithmetic
         * elsewhere in the tree, so the answer at an offset in the middle
         * of a character matters as much as the answer at a boundary.
         */
        (void) printf("kanji1\t%d\t", i);
        for (j = 0; j <= len; j++)
            (void) printf("%d", is_kanji1(s, j) ? 1 : 0);
        (void) printf("\n");

        (void) printf("kanji2\t%d\t", i);
        for (j = 0; j <= len; j++)
            (void) printf("%d", is_kanji2(s, j) ? 1 : 0);
        (void) printf("\n");
    }
}

/* --- split_japanese ------------------------------------------------ */

static void
dump_splits()
{
    int i, pos;

    for (i = 0; jlib_strings[i]; i++) {
        int len = (int) strlen(jlib_strings[i]);

        /*
         * Every break position, including past the end.  topl.c calls this
         * with CO-ish numbers that have nothing to do with where the
         * characters happen to fall.
         */
        for (pos = 0; pos <= len + 2; pos++) {
            char work[512], s1[512], s2[512];

            (void) strcpy(work, jlib_strings[i]);
            (void) memset(s1, 0, sizeof s1);
            (void) memset(s2, 0, sizeof s2);

            split_japanese(work, s1, s2, pos);

            (void) printf("split\t%d\t%d\t[%s]\t[%s]\n", i, pos, s1, s2);

            /*
             * Whatever else it does, it must not lose or invent bytes: the
             * two halves have to rejoin into the input.  Checked here
             * rather than left to the eye, because the golden file only
             * catches a *change*, and this property was worth having even
             * before the rewrite.
             */
            {
                char joined[1024];

                (void) strcpy(joined, s1);
                (void) strcat(joined, s2);
                if (strcmp(joined, jlib_strings[i]) != 0)
                    (void) printf("LOSSY\t%d\t%d\t[%s]\n", i, pos, joined);
            }
        }
    }
}

/* --- jrndm_replace ------------------------------------------------- */

static void
dump_rndm()
{
    int i;

    for (i = 0; jlib_chars[i]; i++) {
        char buf[16];
        int j;

        /* several draws each, since the replacement is random */
        for (j = 0; j < 4; j++) {
            (void) strcpy(buf, jlib_chars[i]);
            jrndm_replace(buf);
            (void) printf("rndm\t%d\t%d\t[%s]\n", i, j, buf);
        }
    }
}

/* --- jnumeral / jcounter ------------------------------------------- */

/*
 * These moved out of src/objnam.c's readobjnam(), where they were twenty
 * strncmp() calls with the byte length written in by hand.  objnam.c cannot
 * be linked standalone, so getting them down here is what makes them
 * testable at all -- which is most of the reason for the move.
 */
static void
dump_numerals()
{
    int i;

    for (i = 0; jlib_words[i]; i++) {
        const char *w = jlib_words[i];
        int len = -1;
        int n = jnumeral(w, &len);

        (void) printf("numeral\t%d\t%d\t%d\n", i, n, n ? len : -1);
        (void) printf("counter\t%d\t%d\n", i, jcounter(w));

        /*
         * A numeral must report the length of the character it matched, not
         * a fixed 2 -- that assumption is the whole reason this file exists.
         * Checked as a property so it fails under --record too.
         */
        if (n && len != mb_seqlen(w))
            (void) printf("BADLEN\t%d\t%d\t%d\n", i, len, mb_seqlen(w));

        /* Likewise a counter word's length must land on a boundary. */
        {
            int c = jcounter(w);

            if (c && !mb_is_boundary(w, c))
                (void) printf("BADCOUNTER\t%d\t%d\n", i, c);
        }
    }
}

int
main()
{
    dump_boundaries();
    dump_splits();
    dump_rndm();
    dump_numerals();
    return 0;
}

/* --- stubs --------------------------------------------------------- */

/*
 * A fixed sequence, not the game's generator: jrndm_replace() is meant to
 * be random, and a transcript of random output cannot be diffed.  The
 * multiplier and addend are the usual ANSI C ones; all that matters is that
 * it is the same every run and reaches every value in range.
 */
static unsigned long rnstate = 1;

int
rn2(x)
int x;
{
    rnstate = rnstate * 1103515245UL + 12345UL;
    return (int) ((rnstate >> 16) % (unsigned long) x);
}

/* Named by jlib.c's joffmsg()/jonmsg(), which this test does not call. */
struct objclass objects[1];

const char *
body_part(part)
int part;
{
    return "body";
}

/* Declared VDECL(...) in extern.h; jlib.c only ever calls it on a path this
   test does not take, so the signature just has to link. */
void
impossible(const char *s, ...)
{
    (void) fprintf(stderr, "impossible: %s\n", s ? s : "");
}

/*jlibtest.c*/
