#!/usr/bin/env python3
"""Generate include/jis0208.h -- the JIS X 0208 to Unicode table.

    ./japanese/mkjis0208.py > include/jis0208.h

The SDL backend puts Unicode code points in cells, but JNetHack's strings
are EUC-JP, so something has to map one to the other.  The alternatives
were rejected:

  * iconv(3) makes the mapping depend on the C library and on a locale
    being installed, which is exactly the dependency the cell grid exists
    to get rid of (see SDL-POC-RESULT.md H3).
  * SDL_iconv_string() only has EUC-JP when SDL itself was built against
    a system iconv, so it is no better and less predictable.

A generated table is 17 KB of .rodata, needs nothing at run time, and
gives the same answer on every machine.  Python's own euc_jp codec is the
source, so regenerating it requires no data files.

Row 1..94, cell 1..94 is stored at (row - 1) * 94 + (cell - 1); zero means
"no character assigned", which is true of a good part of the space.
"""

import sys

ROWS = CELLS = 94


def euc_bytes(row, cell):
    return bytes([0xA0 + row, 0xA0 + cell])


def main():
    table = [0] * (ROWS * CELLS)
    mapped = 0
    for row in range(1, ROWS + 1):
        for cell in range(1, CELLS + 1):
            try:
                ch = euc_bytes(row, cell).decode("euc_jp")
            except UnicodeDecodeError:
                continue
            if len(ch) != 1:
                continue
            table[(row - 1) * CELLS + (cell - 1)] = ord(ch)
            mapped += 1

    out = sys.stdout
    out.write("/*\tjis0208.h\t*/\n")
    out.write("/* JNetHack may be freely redistributed.  See license for"
              " details. */\n\n")
    out.write("/*\n"
              " * JIS X 0208 -> Unicode, generated by japanese/mkjis0208.py.\n"
              " * Do not edit; regenerate.\n"
              " *\n"
              " * Indexed by (row - 1) * 94 + (cell - 1), where row and cell\n"
              " * are the two EUC-JP bytes with 0xA0 subtracted.  A zero entry\n"
              " * means the code point is unassigned in JIS X 0208.\n"
              " *\n"
              " * %d of %d positions are assigned.\n"
              " */\n\n" % (mapped, ROWS * CELLS))
    out.write("#ifndef JIS0208_H\n#define JIS0208_H\n\n")
    out.write("#define JIS0208_ROWS\t%d\n" % ROWS)
    out.write("#define JIS0208_CELLS\t%d\n\n" % CELLS)
    out.write("static const unsigned short jis0208_to_ucs[%d] = {\n"
              % (ROWS * CELLS))
    for row in range(ROWS):
        base = row * CELLS
        out.write("    /* row %d */\n" % (row + 1))
        for i in range(0, CELLS, 8):
            # min() matters: CELLS is not a multiple of 8, and a plain
            # base+i+8 slice would spill into the next row.
            chunk = table[base + i:base + min(i + 8, CELLS)]
            out.write("    " + " ".join("0x%04X," % v for v in chunk) + "\n")
    out.write("};\n\n#endif /* JIS0208_H */\n")


if __name__ == "__main__":
    main()
