#	NetHack Makefile.
#	SCCS Id: @(#)Makefile.dat	3.1	92/09/18

# Set MINGW=1 to build the data files for the Windows binary.  They cannot
# be shared with the host build: the level files and the dungeon are raw
# struct dumps, and Windows is LLP64 where Linux is LP64 (sizeof(long) 4
# against 8, struct you 784 bytes against 1008), which src/version.c
# rejects as "Configuration incompatability for file ...".  The utilities
# are cross-compiled by ../util and run here under wine.
#
# Run this in a directory of its own -- test/build.sh stages one from the
# sources in dat/ -- or it overwrites the host build's data files.
MINGW =
X =
RUN =
ifeq ($(MINGW),1)
X = .exe
RUN = wine
endif

MAKEDEFS = $(RUN) ../util/makedefs$(X)
LEV_COMP = $(RUN) ../util/lev_comp$(X)
DGN_COMP = $(RUN) ../util/dgn_comp$(X)

# by issei 1994/2/5
#VARDAT = data rumors quest.dat oracles options
VARDAT = data jrumors quest.dat joracles options

all:	$(VARDAT) spec_levs quest_levs dungeon

../util/makedefs$(X):
	(cd ../util ; $(MAKE) makedefs$(X))

../util/dgn_comp$(X):
	(cd ../util ; $(MAKE) dgn_comp$(X))

../util/lev_comp$(X):
	(cd ../util ; $(MAKE) lev_comp$(X))

../util/tile2x11$(X):
	(cd ../util ; $(MAKE) tile2x11$(X))

x11tiles: ../util/tile2x11$(X) ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt
	../util/tile2x11$(X) ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt

pet_mark.xbm: ../win/X11/pet_mark.xbm
	cp ../win/X11/pet_mark.xbm pet_mark.xbm

rip.xpm: ../win/X11/rip.xpm
	cp ../win/X11/rip.xpm rip.xpm

data:	data.base ../util/makedefs$(X)
	$(MAKEDEFS) -d

#rumors:	rumors.tru rumors.fal ../util/makedefs$(X)
jrumors:	jrumors.tru jrumors.fal ../util/makedefs$(X)
	$(MAKEDEFS) -r

quest.dat:	quest.txt ../util/makedefs$(X)
	$(MAKEDEFS) -q

# by issei 1994/2/5
#oracles:	oracles.txt ../util/makedefs$(X)
joracles:	joracles.txt ../util/makedefs$(X)
	$(MAKEDEFS) -h

# note: 'options' should have already been made when include/date.h was created
options:	../util/makedefs$(X)
	$(MAKEDEFS) -v


spec_levs: ../util/lev_comp$(X) \
	bigroom.des castle.des endgame.des gehennom.des knox.des medusa.des \
	mines.des oracle.des tower.des yendor.des
	$(LEV_COMP) bigroom.des
	$(LEV_COMP) castle.des
	$(LEV_COMP) endgame.des
	$(LEV_COMP) gehennom.des
	$(LEV_COMP) knox.des
	$(LEV_COMP) medusa.des
	$(LEV_COMP) mines.des
	$(LEV_COMP) oracle.des
	$(LEV_COMP) tower.des
	$(LEV_COMP) yendor.des
	touch spec_levs

quest_levs: ../util/lev_comp$(X) \
	Arch.des Barb.des Caveman.des Elf.des Fighter.des Healer.des Knight.des \
	Priest.des Rogue.des Samurai.des Tourist.des Valkyrie.des Wizard.des
	$(LEV_COMP) Arch.des
	$(LEV_COMP) Barb.des
	$(LEV_COMP) Caveman.des
	$(LEV_COMP) Elf.des
	$(LEV_COMP) Fighter.des
	$(LEV_COMP) Healer.des
	$(LEV_COMP) Knight.des
	$(LEV_COMP) Priest.des
	$(LEV_COMP) Rogue.des
	$(LEV_COMP) Samurai.des
	$(LEV_COMP) Tourist.des
	$(LEV_COMP) Valkyrie.des
	$(LEV_COMP) Wizard.des
	touch quest_levs

dungeon: dungeon.def ../util/makedefs$(X) ../util/dgn_comp$(X)
	$(MAKEDEFS) -e
	$(DGN_COMP) dungeon.pdf

spotless:
	-rm -f spec_levs quest_levs *.lev $(VARDAT) dungeon dungeon.pdf
